name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install Chrome only
      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      # (optional) show version so we know what’s installed
      - name: Print Chrome version
        run: ${{ steps.setup-chrome.outputs.chrome-path }} --version

      # Only run tests (Selenium Manager will download the correct driver if needed)
      - name: Build & Test
        run: mvn -B -ntp test
